services:
  spring-jni:
    image: 'sebastianhenaogamboa/prioridades-no-expulsivas:latest'
    ports:
      - '8093:8093'
    networks:
      - red-backend-app
networks:
  red-backend-app:
    driver: bridge